app = "consulta-pe-wa-v1"
primary_region = "mia" # puedes usar gru, ewr, scl, etc

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
