# fly.toml app configuration file for Consulta PE WhatsApp Bot
# Mantener online 24/7

app = 'consulta-pe-wa-bot'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false   # Evita que Fly.io apague la máquina
  auto_start_machines = true
  min_machines_running = 1     # Siempre habrá al menos 1 máquina corriendo
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
