[phases.setup]
commands = ["echo 'Usando Node.js LTS'"]

[phases.install]
commands = ["curl -fsSL https://deb.nodesource.com/setup_20.x | bash -", "apt-get install -y nodejs"]

[phases.build]
commands = ["echo 'No hay build, solo start'"]

[phases.start]
commands = ["node server.mjs"]
